# Generated by Django 5.0.7 on 2024-07-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='meal_type',
            field=models.CharField(choices=[('starters', 'Starters'), ('salads', 'Salads'), ('main_dishes', 'Main Dishes'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], max_length=200),
        ),
    ]
